### ISSUE TITLE
已知的随机种子导致结果可预测

### ISSUE THREAD

**Issue by ambulong** [zju-cst/DRLS#15]
文件DRLS/drls/rng.py中获取随机数使用外部随机种子：

```pythoom.seed(seed)
        ran = random.uniform(0,self.range)
        return ran
```

第一个随机种子来源于外部文件上传，文件DRLS/drls/public/views.py：

```python
def upload():
    if request.method == 'POST':
        seed = request.form['randomSeed']
        num = request.form['randomNum']
```
已知的随机种子导致结果可预测

**Comment by terasum** [comment]
要求就是可预测，随机种子在真正抽签之时确定。

**Comment by ambulong** [comment]
结果已知的话还抽签干嘛

**Comment by terasum** [comment]
@ambulong 随机种子是现场随机选择的，要求是能够在给定随机种子的前提下，结果是一样的，
结果直到抽签之前都是不知道的，随机种子是需要现场确定的。

**Comment by terasum** [comment]
要求就是随机过程可重现 @ambulong

**Comment by ambulong** [comment]
这样不就还要一个生成随机种子的程序

**Comment by terasum** [comment]
这种东西不是很简单的么，随便python现场rand不就好了

**Comment by ambulong** [comment]
0~10000之间的随机数作为第一个随机种子后生成的第一个随机数的概率也不一样哪。

**Comment by terasum** [comment]
伪随机数的生成确实是不一样的，但是不在我们的考虑范围之内，我们假定随机种子给出是经过大家同意的。
